image: node:15-buster

stages:
    - build
    - test
    - deploy
    - release

cache:
    paths:
        - node_modules/

variables:
    REACT_APP_STATIC_PAGE_ONLY: "false"

workflow:
    rules:
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH

.only-refs: &only_refs
    only:
        - master
        - prod
        - dev
        - rococo
        - beta
        - tags

services:
    - name: registry.gitlab.com/interlay/btc-parachain:master-1b4a8dc5-1622454849
      alias: btc-parachain
      command:
          - btc-parachain
          - --rpc-external
          - --ws-external
          - --rpc-methods
          - Unsafe
          - --dev
    - image: "ruimarinho/bitcoin-core:0.21"
      alias: bitcoind
      command:
          - -regtest
          - -server
          - -rpcbind=0.0.0.0
          - -rpcallowip=0.0.0.0/0
          - -rpcuser=rpcuser
          - -rpcpassword=rpcpassword
          - -fallbackfee=0.0002
    - image: "registry.gitlab.com/interlay/polkabtc-clients/faucet:0-7-5"
      alias: faucet
      command:
          - /bin/sh
          - -c
          - |
              echo '{"bob_stash": "0x1a7d114100653850c65edecda8a9b2b4dd65d900edef8e70b1a6ecdcda967056"}' > keyfile.json
              echo "Sleeping..."
              sleep 5
              faucet --keyfile="keyfile.json" --keyname=bob_stash --btc-parachain-url 'ws://localhost:9944' --user-allowance 1 --vault-allowance 500 --http-addr '[::0]:3036'

build:
    stage: build
    script:
        - yarn
        - yarn build
    artifacts:
        expire_in: 1 day
        paths:
            - build

test-release:
    stage: test
    script:
        - yarn
        - yarn ci:test

build_container:
    stage: deploy

    image:
        name: gcr.io/kaniko-project/executor:v1.5.1-debug
        entrypoint: [""]
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - |
            /kaniko/executor --context $CI_PROJECT_DIR \
              --dockerfile $CI_PROJECT_DIR/DockerfileProd \
              --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}-$CI_COMMIT_SHORT_SHA \
              --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}
    <<: *only_refs

github_changelog:
    stage: release
    image: registry.gitlab.com/interlay/containers/github-publisher:master
    script:
        - gh auth status
        - git-chglog --output CHANGELOG.md $CI_COMMIT_TAG
        - gh release -R https://github.com/interlay/polkabtc-ui create $CI_COMMIT_TAG --title $CI_COMMIT_TAG -F CHANGELOG.md -d
    only:
        - tags
