name: test

on:
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                registry: registry.gitlab.com
                username: ${{ secrets.GITLAB_USERNAME }}
                password: ${{ secrets.GITLAB_TOKEN }}
            - name: Run and set up the parachain, oracle, staked relayer and vault
              run: docker-compose up -d
            - run: yarn install
            - run: yarn ci:test:staging
